#!/usr/bin/env python3
"""
Regenerate ``src/generated/schema_types.py`` from JSON files under ``schemas/``.

This is a **minimal deterministic stub** until the monorepo publishes a full
``datamodel-codegen`` (or equivalent) pipeline. CI uses ``--check`` to fail on drift.

Usage:
  python3 codegen/gen_types.py
  python3 codegen/gen_types.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCHEMAS = _REPO_ROOT / "schemas"
_OUT = _REPO_ROOT / "src" / "generated" / "schema_types.py"


def _manifest() -> tuple[str, list[tuple[str, str]]]:
    """Return (combined_sha256_hex, [(relpath, file_sha256), ...])."""
    entries: list[tuple[str, str]] = []
    if not _SCHEMAS.is_dir():
        return "0" * 64, []
    for path in sorted(_SCHEMAS.glob("*.json")):
        rel = path.relative_to(_REPO_ROOT).as_posix()
        raw = path.read_bytes()
        h = hashlib.sha256(raw).hexdigest()
        entries.append((rel, h))
    cat = "".join(f"{rel}\n{h}\n" for rel, h in entries)
    combined = hashlib.sha256(cat.encode("utf-8")).hexdigest() if cat else "0" * 64
    return combined, entries


def render() -> str:
    combined, files = _manifest()
    lines = [
        "# Generated by codegen/gen_types.py — do not edit by hand.",
        "# Regenerate: python3 codegen/gen_types.py",
        f"SCHEMA_BUNDLE_SHA256 = {combined!r}",
        "SCHEMA_FILES: dict[str, str] = {",
    ]
    for rel, h in files:
        lines.append(f"    {rel!r}: {h!r},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def load_schema_json(relative_name: str) -> dict:")
    lines.append('    """Load a JSON object from ``schemas/<relative_name>`` (repo root)."""')
    lines.append("    from pathlib import Path")
    lines.append("    root = Path(__file__).resolve().parents[2]")
    lines.append("    p = root / \"schemas\" / relative_name")
    lines.append("    import json")
    lines.append("    return json.loads(p.read_text(encoding=\"utf-8\"))")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if ``schema_types.py`` would change.",
    )
    args = ap.parse_args()
    body = render()
    if args.check:
        cur = _OUT.read_text(encoding="utf-8") if _OUT.is_file() else ""
        if cur != body:
            sys.stderr.write(
                f"Drift: {_OUT} is out of date. Run: python3 codegen/gen_types.py\n"
            )
            return 1
        return 0
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
